apiVersion: v1
kind: Namespace
metadata:
  name: onboarding
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secret-store
  namespace: onboarding
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: onboarding
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::246312965731:role/external-secrets-role
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: onboarding
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: onboarding/db-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: onboarding/db-credentials
        property: password
    - secretKey: host
      remoteRef:
        key: onboarding/db-credentials
        property: host
    - secretKey: dbname
      remoteRef:
        key: onboarding/db-credentials
        property: dbname
